parameters:
    chatgpt:
        model: 'gpt-3.5-turbo'
        max_tokens: 1000
        temperature: 0.7
        system_message: 'あなたは親切で丁寧な日本語のアシスタントです。簡潔で分かりやすい返答を心がけてください。'
        error_messages:
            payment_required: 'OpenAIアカウントの支払い情報を確認してください。'
            general_error: 'すみません、一時的に返答できません。しばらく経ってから再度お試しください。'