# Production environment compose file
# Usage: docker compose -f compose.yaml -f compose.prod.yaml up -d

services:
  app:
    environment:
      - APP_ENV=prod
      - APP_DEBUG=0
    command: >
      sh -c "
        composer install --no-dev --optimize-autoloader &&
        php bin/console cache:clear --env=prod &&
        php bin/console doctrine:database:create --if-not-exists &&
        php bin/console doctrine:schema:update --force &&
        php bin/console messenger:setup-transports &&
        supervisord -c /etc/supervisord.conf
      "

  worker:
    environment:
      - APP_ENV=prod
      - APP_DEBUG=0
    command: >
      sh -c "
        composer install --no-dev --optimize-autoloader &&
        php bin/console cache:clear --env=prod &&
        php bin/console messenger:consume async -vv
      "

  # Production database without exposed port
  database:
    ports: []
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data: